name: .NET Core

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Only do this when tagged
      run: echo "Hello tag ${{ github.ref }}"
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: cd Calc && dotnet publish --runtime osx.10.14-x64 -c Release -o ./deploy
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Calc
        path: Calc/deploy/Calc
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
          Calc/deploy/Calc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
