name: .NET Core

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Calc
        path: Calc/bin/Release/netcoreapp3.1/osx.10.14-x64/Calc
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
          Calc/bin/Release/netcoreapp3.1/osx.10.14-x64/Calc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
